name: lead_gen
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+6

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.1.14
  flutter_bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  either_dart: ^1.0.0
  flutter_local_notifications: ^16.3.3
  timezone: ^0.9.2
  get_it: ^7.6.7
  http: ^1.1.0
  email_validator: ^2.1.17
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  fluttertoast: ^8.2.4
#  firebase_core: ^2.24.1
#  firebase_messaging: ^14.7.9
  device_info_plus: ^9.1.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  intl: ^0.19.0
  google_fonts: 6.1.0
  table_calendar: ^3.1.1
  firebase_messaging: ^14.7.19
  firebase_core: ^2.27.0
  googleapis_auth: ^1.4.2
  flutter_html: 3.0.0-alpha.6
  package_info_plus: ^5.0.1
  in_app_update: ^4.2.3
  flutter_contacts: ^1.1.9+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/app-icon.png"


flutter:


  uses-material-design: true
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
